/* ===================================================================
   DÜZENLENECEK İÇERİK DOSYASI
   Bu dosyadaki bilgileri kendi firmanıza göre güncelleyin.
   Kod bilgisi gerekmez — sadece tırnak içindeki metinleri değiştirin.

   NOT: Google E-Tablosu bağladığınızda (BRAND.listingsSheetUrl) bu
   LISTINGS dizisi yalnızca tablo erişilemezse YEDEK olarak kullanılır.
   =================================================================== */

const BRAND = {
  name: "Hande Eren",
  fullName: "Hande Eren Gayrimenkul Danışmanlığı",
  tagline: "Kadıköy & İstanbul Gayrimenkul Danışmanı",
  phoneDisplay: "0532 628 08 98",
  whatsapp: "905326280898",
  email: "hande.eren@kww.com.tr",
  addressLines: ["Keller Williams Cadde", "Kadıköy, İstanbul"],
  mapQuery: "Keller Williams Cadde Kadıköy İstanbul",
  hours: "Hafta içi 09:00–19:00, Cumartesi 10:00–17:00",
  social: {
    instagram: "#",
    facebook: "#",
    linkedin: "#"
  },
  listingsSheetUrl: ""
};

/* İlanlar — her biri bir satılık/kiralık örnek mülk.
   "art" alanı, gerçek fotoğraf (images dizisi) yoksa kart/detay
   sayfasında gösterilecek çizim stilini belirler: villa | apart | office | land
   "status": aktif | satildi | kiralandi
   "images": gerçek fotoğraf bağlantıları — boşsa otomatik çizim kullanılır */
const LISTINGS = [
  {
    id: 1,
    title: "Bahçeli, ferah aile dairesi",
    titleEn: "Spacious family apartment with garden",
    district: "Kadıköy",
    neighborhood: "Moda",
    category: "Konut",
    type: "Daire",
    deal: "satilik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 8750000,
    discountedPrice: null,
    grossArea: 150,
    netArea: 135,
    rooms: "3+1",
    buildingAge: 8,
    floor: 2,
    totalFloors: 5,
    status: "aktif",
    featured: true,
    art: "apart",
    images: [],
    desc: "Sakin bir sokakta, güneye bakan, yenilenmiş bir 3+1.",
    descEn: "A renovated 3+1 facing south, on a quiet street."
  },
  {
    id: 2,
    title: "Boğaz manzaralı geniş villa",
    titleEn: "Spacious villa with Bosphorus view",
    district: "Beykoz",
    neighborhood: "Kanlıca",
    category: "Konut",
    type: "Villa",
    deal: "satilik",
    tapuDurumu: "Müstakil Tapu",
    price: 42000000,
    discountedPrice: 39500000,
    grossArea: 340,
    netArea: 310,
    rooms: "5+2",
    buildingAge: 4,
    floor: null,
    totalFloors: 3,
    status: "aktif",
    featured: true,
    art: "villa",
    images: [],
    desc: "Özel bahçeli, kapalı otoparklı, sitenin en üst noktasında.",
    descEn: "Private garden, closed garage, at the highest point of the site."
  },
  {
    id: 3,
    title: "Merkezi konumda kiralık ofis",
    titleEn: "Office for rent in a central location",
    district: "Şişli",
    neighborhood: "Esentepe",
    category: "Ticari",
    type: "Ofis",
    deal: "kiralik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 95000,
    discountedPrice: null,
    grossArea: 200,
    netArea: 180,
    rooms: "Açık ofis",
    buildingAge: 12,
    floor: 7,
    totalFloors: 18,
    status: "aktif",
    featured: false,
    art: "office",
    images: [],
    desc: "Metro durağına 5 dakika, hazır altyapılı plaza katı.",
    descEn: "5 minutes to the metro station, ready-to-use plaza floor."
  },
  {
    id: 4,
    title: "Yeni yapı, asansörlü kiralık daire",
    titleEn: "New-build apartment for rent with elevator",
    district: "Üsküdar",
    neighborhood: "Acıbadem",
    category: "Konut",
    type: "Daire",
    deal: "kiralik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 32000,
    discountedPrice: null,
    grossArea: 105,
    netArea: 95,
    rooms: "2+1",
    buildingAge: 0,
    floor: 4,
    totalFloors: 9,
    status: "aktif",
    featured: false,
    art: "apart",
    images: [],
    desc: "Sıfır bina, otoparklı, markete yürüme mesafesinde.",
    descEn: "Brand-new building, with parking, walking distance to the market."
  },
  {
    id: 5,
    title: "Yatırımlık imarlı arsa",
    titleEn: "Zoned land, suitable for investment",
    district: "Çekmeköy",
    neighborhood: "Reşadiye",
    category: "Arsa",
    type: "Arsa",
    deal: "satilik",
    tapuDurumu: "Arsa Tapulu",
    price: 6200000,
    discountedPrice: null,
    grossArea: 800,
    netArea: 800,
    rooms: "—",
    buildingAge: null,
    floor: null,
    totalFloors: null,
    status: "aktif",
    featured: true,
    art: "land",
    images: [],
    desc: "Yola cepheli, imar durumu net, tapu hazır.",
    descEn: "Road-facing, zoning status clear, deed ready."
  },
  {
    id: 6,
    title: "Deniz manzaralı dubleks daire",
    titleEn: "Duplex apartment with sea view",
    district: "Beşiktaş",
    neighborhood: "Levent",
    category: "Konut",
    type: "Daire",
    deal: "satilik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 26500000,
    discountedPrice: null,
    grossArea: 180,
    netArea: 165,
    rooms: "4+1",
    buildingAge: 6,
    floor: 9,
    totalFloors: 10,
    status: "satildi",
    featured: false,
    art: "apart",
    images: [],
    desc: "Çift cephe, kışın da deniz manzarası kaybolmuyor.",
    descEn: "Dual aspect, the sea view doesn't disappear even in winter."
  },
  {
    id: 7,
    title: "Sahil şeridinde kiralık villa",
    titleEn: "Villa for rent on the coastline",
    district: "Bodrum",
    neighborhood: "Gümüşlük",
    category: "Konut",
    type: "Villa",
    deal: "kiralik",
    tapuDurumu: "Müstakil Tapu",
    price: 180000,
    discountedPrice: null,
    grossArea: 240,
    netArea: 220,
    rooms: "4+1",
    buildingAge: 3,
    floor: null,
    totalFloors: 2,
    status: "aktif",
    featured: false,
    art: "villa",
    images: [],
    desc: "Yazlık veya yıllık kiralanabilir, özel havuzlu.",
    descEn: "Available as a seasonal or yearly rental, with a private pool."
  },
  {
    id: 8,
    title: "Cadde üzeri kiralık dükkan",
    titleEn: "Shop for rent on the main street",
    district: "Beşiktaş",
    neighborhood: "Levent",
    category: "Ticari",
    type: "Dükkan",
    deal: "kiralik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 65000,
    discountedPrice: null,
    grossArea: 65,
    netArea: 60,
    rooms: "Tek kat",
    buildingAge: 15,
    floor: 0,
    totalFloors: 4,
    status: "kiralandi",
    featured: false,
    art: "office",
    images: [],
    desc: "Yoğun yaya trafiği olan ana cadde üzerinde köşe dükkan.",
    descEn: "Corner shop on a high-foot-traffic main street."
  },
  {
    id: 9,
    title: "Bahçe katı, hobi bahçeli daire",
    titleEn: "Garden-floor apartment with hobby garden",
    district: "Çekmeköy",
    neighborhood: "Reşadiye",
    category: "Konut",
    type: "Daire",
    deal: "satilik",
    tapuDurumu: "Kat Mülkiyetli",
    price: 11900000,
    discountedPrice: 11400000,
    grossArea: 155,
    netArea: 142,
    rooms: "3+1",
    buildingAge: 5,
    floor: 0,
    totalFloors: 4,
    status: "aktif",
    featured: false,
    art: "apart",
    images: [],
    desc: "Sitenin en sakin bloğunda, özel kullanım bahçeli.",
    descEn: "In the quietest block of the complex, with a private-use garden."
  }
];

/* Danışman profili — solo kullanım */
const TEAM = [
  {
    id: 1,
    name: "Hande Eren",
    role: "Gayrimenkul Danışmanı",
    bio: "1977 İstanbul doğumlu. Nişantaşı Kız Lisesi ve Uludağ Üniversitesi İşletme mezunu. Bankacılık, finansman ve lojistik sektörlerinde 20 yıllık kurumsal tecrübesiyle gayrimenkul sektörüne adım attı. Keller Williams Cadde bünyesinde, analitik bakış açısı ve güçlü müşteri ilişkileriyle Kadıköy başta olmak üzere tüm İstanbul'da alıcı ve satıcılara danışmanlık yapıyor. Taşınmaz Ticareti Yetki Belge No: 3403812-264",
    phoneDisplay: "0532 628 08 98",
    email: "hande.eren@kww.com.tr",
    photo: "img/hande-eren.jpg"
  }
];
